{{- /*
This file was autogenerated by helmify-kustomize
DO NOT EDIT: Any changes will be overwritten
*/ -}}
{{- define "hlmfk-1-2-e3ed083448.valuesYaml" -}}
{{- $runtime_nodeSelector := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "nodeSelector") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_secret_name := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "secretName") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_registry := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "registry") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_app_tag := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "appVersion") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_replicas := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "replicas") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_namespace := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "namespace") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $anchor_namespace_default := printf `webrix-mcp-s` -}}
{{- $anchor_replicas_default := printf `1` -}}
{{- $anchor_app_tag_default := printf `latest` -}}
{{- $anchor_registry_default := printf `quay.io/idan-chetrit/mcp-s-app` -}}
{{- $anchor_secret_name_default := printf `mcp-s-app-container-secret-vars` -}}
{{- $anchor_nodeSelector_default := printf `prometheus.io/scrape: test` -}}
{{- $final_namespace := "" -}}
{{- if eq $runtime_namespace "__HELMIFY_NOT_FOUND__" -}}
{{- $final_namespace = $anchor_namespace_default -}}
{{- else -}}
{{- $final_namespace = $runtime_namespace -}}
{{- end -}}
{{- $final_replicas := "" -}}
{{- if eq $runtime_replicas "__HELMIFY_NOT_FOUND__" -}}
{{- $final_replicas = $anchor_replicas_default -}}
{{- else -}}
{{- $final_replicas = $runtime_replicas -}}
{{- end -}}
{{- $final_app_tag := "" -}}
{{- if eq $runtime_app_tag "__HELMIFY_NOT_FOUND__" -}}
{{- $final_app_tag = $anchor_app_tag_default -}}
{{- else -}}
{{- $final_app_tag = $runtime_app_tag -}}
{{- end -}}
{{- $final_registry := "" -}}
{{- if eq $runtime_registry "__HELMIFY_NOT_FOUND__" -}}
{{- $final_registry = $anchor_registry_default -}}
{{- else -}}
{{- $final_registry = $runtime_registry -}}
{{- end -}}
{{- $final_secret_name := "" -}}
{{- if eq $runtime_secret_name "__HELMIFY_NOT_FOUND__" -}}
{{- $final_secret_name = $anchor_secret_name_default -}}
{{- else -}}
{{- $final_secret_name = $runtime_secret_name -}}
{{- end -}}
{{- $final_nodeSelector := "" -}}
{{- if eq $runtime_nodeSelector "__HELMIFY_NOT_FOUND__" -}}
{{- $final_nodeSelector = $anchor_nodeSelector_default -}}
{{- else -}}
{{- $final_nodeSelector = $runtime_nodeSelector -}}
{{- end -}}
# globals:
#  namespace: "namespace"
#  namePrefix: "namePrefix"
#  nameSuffix: "nameSuffix"
#  nameReleasePrefix: "nameReleasePrefix"
#  labels:
#    key: "label"
#  annotations:
#    key: "annotation"
#  images:
#    - image: "old-image"
#      newName: "new-image"
#      newTag: "new-tag"
#      digest: "digest"
#      pullSecrets:
#        - name: "pull-secret"
#  resources:
#    - name: "resource"
#      version: "v1"
#      kind: "Resource"
overlay: "overlays/on-prem"
namespace: &namespace {{ $final_namespace }}
replicas: &replicas {{ $final_replicas }}
appVersion: &app_tag {{ $final_app_tag }}
registry: &registry {{ $final_registry }}
secretName: &secret_name {{ $final_secret_name }}
nodeSelector: &nodeSelector 
{{ $final_nodeSelector | indent 2 }}
globals:
  addStandardHeaders: false
  images:
    - image: quay.io/idan-chetrit/mcp-s-app
      newTag: {{ $final_app_tag }}
      newName: {{ $final_registry }}
  namespace: {{ $final_namespace }}
  patches:
    - target:
        kind: Deployment
        name: mcp-s-app
      ops:
        - op: add
          path: /spec/replicas
          value: {{ $final_replicas }}
        - op: add
          path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
          value: {{ $final_secret_name }}
        - op: add
          path: /spec/template/spec/nodeSelector
          value: {{ $final_nodeSelector | fromYaml | toYaml | nindent 12 }}
env:
  DB_BASE_URL: http://mcp-s-db-service
  AUTH_SECRET: aUi2V5iCVqUrbrdjKty1zH4HCqszXArV9BLVU2giqhY=
  DB_AUTH_SECRET: ZI39UlR2sN6HFZauuze0iNEZnNkF1wiOuGklm3bC8dk=
  PORT: "3000"
  ORG: on-prem-org
  ON_PREM: "true"

{{- end -}}